MODULES:
  - "image_managers"
  - "vae"
  - "diffsuion"
  - "latent_diffusion"
  - "unet"

image_manager:
  CLASS: "Cifar10Manager"
  data_root: "../data"

vae:
  model:
    CLASS: "VAE"
    num_latents: 4
    beta: 1.0
    stage_depths: [4, 4, 4]
    channels: 48
    channel_mults: [1, 2, 1]
    learning_rate: 0.0001
    weight_decay: 0.01
    x_logvar_learning_rate: 0.001

  max_epochs: 20
  batch_size: 64
  gradient_clip_val: 1.0
  swa_lrs: 0.00001


latent_diffusion:
  model:
    ClASS: "LatentDiffusion"
    diffusion:
      CLASS: "Diffusion"
      network:
        CLASS: "UNet"
        input_channels: 4
        input_size: 8
        channels: 128
        num_blocks: [4, 4, 2]
        channel_mults: [1, 2, 4]
        attn_resolutions: [16, 8, 4]
      time_steps: 1000
      learning_rate: 0.0001
      weight_decay: 0.1

  max_epochs: 1000
  batch_size: 64
  gradient_clip_val: 1.0
  swa_lrs: 0.00002